[project]
name = "chess-client"
version = "0.1.0"
description = "Chess client for the ChessBeez Hackathon"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "chess>=1.11.1",
    "pydantic-settings>=2.7.0",
    "websockets>=14.1",
]
